### ISSUE TITLE
version, tag, and create releases

### ISSUE THREAD

**Issue by joelb123** [rcedgar/muscle#1]
The version info for muscle5 is contained in ver_counter.h (referenced incorrectly in the code itself as ../ver/counter.h).  This file contains a version string of 1219, while the executable in the binaries directory shows 1278.  There are no tags or releases.

Please fix the file reference, preferably renaming it to the standard "version.h".   Then tag and create a release.

The[ release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/about-releases) is where the binaries should live, not in the repo.  You will care if you are creating releases frequently and run out of push bandwidth.

**Comment by rcedgar** [comment]
ver_counter.h fixed. Thanks for the feedback on github conventions, the learning curve for git[hub] is quite steep, will keep these points in mind longer term.

**Comment by joelb123** [comment]
Let me help you along your learning path.  You want the command "git tag v5.0.1278" and then "git push origin main --tags". But you didn't change the version number in ver_counter.h
