### ISSUE TITLE
Fatal error mpcflat.cpp assert failed

### ISSUE THREAD

**Issue by jianshu93** [rcedgar/muscle#11]
muscle 5.0.1428_linux64  791Gb RAM, 24 cores
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

Hello Robert,

I have the following error when running muscle. There supper5 one is good.

muscle -align ASVs1.fa -output aln.afa -threads 24
Elapsed time 01:27:16
Max memory 0.0b

---Fatal error---
mpcflat.cpp(170) assert failed: PairCount == PairCount2
5140.18user 87.93system 1:27:24elapsed 99%CPU (0avgtext+0avgdata 194959560maxresident)k
62000inputs+24outputs (11major+41593028minor)pagefaults 0swaps

Thanks,

Jianshu

**Comment by rcedgar** [comment]
If you can post ASVs1.fa, happy to take a look. However, I'm going to bet ASVs are 16S or ITS, in which case making an MSA is probably a bad idea, these genes are much too diverse in a typical sample. Why are you aligning them?

**Comment by rcedgar** [comment]
Closed due to no response.
