### ISSUE TITLE
allocflat.cpp(15) assert failed: uint64(Size) == Size64

### ISSUE THREAD

**Issue by Runsheng** [rcedgar/muscle#12]
Dear Robert,

I am running muscle5 (binary or self-compiled binary) on a ubuntu 18.04 machine, and this error message appeared when trying to align more than 1 sequences

---Fatal error---
allocflat.cpp(15) assert failed: uint64(Size) == Size64---Fatal error---
allocflat.cpp(15) assert failed: uint64(Size) == Size64

The order is as follows, 
`muscle5 -super5 allde.fasta -output aln.afa`

Best regards,
Runsheng

**Comment by rcedgar** [comment]
What are the sequence lengths? I'll bet these are very long sequences which are not globally alignable (so you should not be using muscle).

**Comment by Runsheng** [comment]
> What are the sequence lengths? I'll bet these are very long sequences which are not globally alignable (so you should not be using muscle).

Thank you. Yes, the sequences are from DNA viruses with an average length of around 180K. I will separate them into gene chunks and do the alignment separately.

**Comment by shangguan77** [comment]
Hello, I'm also experiencing the same issue. Can you explain how gene blocks are compared and how they are merged afterwards?

**Comment by shangguan77** [comment]
> > What are the sequence lengths? I'll bet these are very long sequences which are not globally alignable (so you should not be using muscle).
> 
> Thank you. Yes, the sequences are from DNA viruses with an average length of around 180K. I will separate them into gene chunks and do the alignment separately.

Hello, I'm also facing the same issue. What criteria are gene chunks divided by? Thank you very much
