### ISSUE TITLE
showing Fatal Error i dont know much about it sorry new guy

### ISSUE THREAD

**Issue by IRSINGH27** [rcedgar/muscle#13]
it happened after it  was joining the
01:51:25 901Mb   100.0% Join 81 / 250 [1 x 717, 717 pairs]
01:51:54 901Mb   100.0% Join 82 / 250 [2 x 718, 1436 pairs]
01:52:05 901Mb   100.0% Join 83 / 250 [1 x 720, 720 pairs]
01:52:13 901Mb   100.0% Join 84 / 250 [1 x 721, 721 pairs]
01:52:14 901Mb   100.0% Join 85 / 250 [1 x 722, 722 pairs]
01:52:25 917Mb   100.0% Join 86 / 250 [2 x 723, 1446 pairs]
01:52:34 910Mb   100.0% Join 87 / 250 [2 x 725, 1450 pairs]
01:52:50 911Mb   100.0% Join 88 / 250 [5 x 727, 2000 pairs]
01:52:58 911Mb   100.0% Join 89 / 250 [1 x 732, 732 pairs]
01:53:10 910Mb   100.0% Join 90 / 250 [1 x 733, 733 pairs]
01:53:53 910Mb   100.0% Join 91 / 250 [5 x 734, 2000 pairs]
01:54:00 910Mb   100.0% Join 92 / 250 [1 x 739, 739 pairs]
01:54:05 910Mb   100.0% Join 93 / 250 [1 x 740, 740 pairs]
01:54:09 910Mb   100.0% Join 94 / 250 [1 x 741, 741 pairs]
01:54:14 910Mb   100.0% Join 95 / 250 [1 x 742, 742 pairs]
01:54:18 910Mb   100.0% Join 96 / 250 [1 x 743, 743 pairs]
01:54:46 910Mb   100.0% Join 97 / 250 [24 x 744, 2000 pairs]
01:54:53 911Mb   100.0% Join 98 / 250 [1 x 768, 768 pairs]
01:54:57 910Mb   100.0% Join 99 / 250 [1 x 769, 769 pairs]
01:55:05 910Mb   100.0% Join 100 / 250 [1 x 770, 770 pairs]
01:55:23 910Mb   100.0% Join 101 / 250 [1 x 771, 771 pairs]
01:55:39 912Mb   100.0% Join 102 / 250 [7 x 772, 2000 pairs]
01:56:11 910Mb   100.0% Join 103 / 250 [2 x 779, 1558 pairs]
01:56:26 910Mb   100.0% Join 104 / 250 [1 x 781, 781 pairs]
01:56:44 910Mb   100.0% Join 105 / 250 [2 x 782, 1564 pairs]
01:56:44 910Mb   100.0% Join 106 / 250 [1 x 2, 2 pairs]
01:56:44 910Mb   100.0% Join 107 / 250 [1 x 1, 1 pairs]
01:56:44 910Mb   100.0% Join 108 / 250 [1 x 2, 2 pairs]
01:56:44 929Mb   100.0% Join 109 / 250 [3 x 4, 12 pairs]
01:56:44 916Mb   100.0% Join 110 / 250 [2 x 7, 14 pairs]
01:56:44 916Mb   100.0% Join 111 / 250 [1 x 9, 9 pairs]
01:56:44 910Mb   100.0% Join 112 / 250 [1 x 2, 2 pairs]
01:56:57 910Mb   100.0% Join 113 / 250 [93 x 240, 2000 pairs]
01:57:11 910Mb   100.0% Join 114 / 250 [160 x 333, 2000 pairs]

muscle -super5 1_newfile.fasta -output aln.afa
Elapsed time 01:57:11
Max memory 1.2Gb

---Fatal error---
AssertSeqsEq E:\src\muscle5\pprog2.cpp:32

**Comment by rcedgar** [comment]
That looks like a bug, the error message at the end is internal check that failed -- not designed to be understandable for users. I will take a look at this if you can post the following: 1. the input file, 2. the exact command line, 3. o/s you are using, e.g. Windows 11, Ubuntu 20.04.

**Comment by IRSINGH27** [comment]
> That looks like a bug, the error message at the end is internal check that failed -- not designed to be understandable for users. I will take a look at this if you can post the following: 1. the input file, 2. the exact command line, 3. o/s you are using, e.g. Windows 11, Ubuntu 20.04.
 muscle -super5  1_Seq_file.fa -output MSA_RESULT.afa 
 this was the command i used
and for system info
Windows 10 Home Single Language 64-bit (10.0, Build 19043) (19041.vb_release.191206-1406) RAM-8gb
input file is following zip
[1_newfile.zip](https://github.com/rcedgar/muscle/files/7609429/1_newfile.zip)

**Comment by rcedgar** [comment]
The problem is caused because your input file has different sequences with the same FASTA label, for example `Streptomyces cattleya NRRL 8057 = DSM 46488:Bacteria`. For sure, muscle should handle this scenario more gracefully. For now, you can work around the problem by making sure all labels are unique.

**Comment by IRSINGH27** [comment]
> The problem is caused because your input file has different sequences with the same FASTA label, for example `Streptomyces cattleya NRRL 8057 = DSM 46488:Bacteria`. For sure, muscle should handle this scenario more gracefully. For now, you can work around the problem by making sure all labels are unique.

ohh Thanks sorry for such dummy mistake  i  will make labels uniques and try running it again thanks
