### ISSUE TITLE
-maketree is showing invalid command line

### ISSUE THREAD

**Issue by IRSINGH27** [rcedgar/muscle#14]
muscle -maketree -in MSA_RESULT.afa -out re.phy

Invalid command line
Unknown option maketree

muscle version- 
muscle 5.0.1428_win64

**Comment by rcedgar** [comment]
maketree is not a command in v5 (it is an old command in v3).

**Comment by IRSINGH27** [comment]
> maketree is not a command in v5 (it is an old command in v3).

so for making tree do we have some new commands or we have download v3?

**Comment by rcedgar** [comment]
Muscle is for making alignments, not trees -- why are you using maketree?

**Comment by IRSINGH27** [comment]
> Muscle is for making alignments, not trees -- why are you using maketree?

because i want to see phylogeny relationship between sequences after msa and onlive converter or mega is not able to do so thats why i was looking if muscle has some inbuilt feature for it

**Comment by rcedgar** [comment]
muscle (any version) is not designed to make accurate phylogenetic trees, you should use a different algorithm.
