### ISSUE TITLE
source files are missing

### ISSUE THREAD

**Issue by joelb123** [rcedgar/muscle#2]
ScoreType.h and FileBuffer.h are referenced in the code but not included with the release.  They seem to come from[ amap](https://petrov.stanford.edu/software/src/amap/), which is not listed as a dependency.

This is the first barrier that anybody wishing to build the code will run into.

**Comment by rcedgar** [comment]
This is not correct. The files `scoretype.h` and `filebuffer.h` (all lower case) are included in the repo and make completes successfully after fixing the `ver_counter.h` bug (which was correct).

**Comment by joelb123** [comment]
No, if you look at probcons.h it contains #include "ScoreType.h".  FileBuffer.h ref is contained in sequence.h.  I checked against the repo just now.

**Comment by rcedgar** [comment]
Yes you were right, sorry about that. Bad grepping, plus I'm running Ubuntu under WSL which apparently considers ScoreType.h and scoretype.h to be the same file, as does Visual Studio -- lesson learned. Thanks for the catch. Fixed now, hopefully :-}
