### ISSUE TITLE
maxgapfract not working in Muscle 5.1.linux64 [12f0e2]

### ISSUE THREAD

**Issue by lukaszsobala** [rcedgar/muscle#26]
Hello,

just a quick issue - the maxgapfract option doesn't seem to work:

`muscle5 -resample sequences.ensemble.efa -maxgapfract 0.3 -output sequences.ensemble.gap03.efa`

the output:
```

Invalid command line
Unknown option maxgapfract

```
Am I doing something wrong?

Thanks,
Lukasz

**Comment by rcedgar** [comment]
That's a bug in the help, the option should be `max_gap_fract`, sorry about that!

**Comment by lukaszsobala** [comment]
Thank you @rcedgar

**Comment by nieder** [comment]
Still present in 5.1.0
