### ISSUE TITLE
Unknown option addconfseqs

### ISSUE THREAD

**Issue by KSteffen** [rcedgar/muscle#30]
Hej Robert!
I'm running muscle5 on a computing cluster and all seems to work super smooth, but I've run into a small issue when trying to calculate the column confidence. 

`muscle -addconfseqs Gene_0107_diversified_ensemble.efa -output Gene_0107_diversified_ensemble_confseqs.efa`

Below the output from the log file:

Invalid command line
Unknown option addconfseqs

muscle 5.1.linux64 []  131Gb RAM, 20 cores
Built Mar 29 2022 15:27:13
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

Is this an issue at my end or yours?
Cheers,
Karin

**Comment by rcedgar** [comment]
My end, typo in the help, the command should be `-addconfseq` (no final S), sorry about that!
