### ISSUE TITLE
Segfault with long sequences

### ISSUE THREAD

**Issue by rcedgar** [rcedgar/muscle#31]
To align a pair of sequences of length L, muscle requires at least 5 x L^2 bytes of memory

The upper limit on L is currently a bit less than 30,000 letters. Unfortunately, this is close to the length of a Cov-2 genome, and an attempt to align Cov-2 genomes with muscle usually fails for this reason.

Currently, muscle segfaults if this limit is exceeded, this is a bug, it should give a graceful error message and exit.

**Comment by fzyxh** [comment]
So if there any solution to align long sequences of length over 30,000?

**Comment by rcedgar** [comment]
not at the moment, sorry.
