### ISSUE TITLE
CLUSTALW and MSF format

### ISSUE THREAD

**Issue by ErisonChen** [rcedgar/muscle#32]
hi @rcedgar 
     with muscle v5.  How could i output aligned file with the clustalw or GCG MSC format.

Thanks a lot

**Comment by ErisonChen** [comment]
And another questions:
    how could i manually set  the cpu and cores the muslce used.

`muscle 5.1.linux64 []  65.6Gb RAM, 40 cores`

this is prettty huge of `65.6Gb` and  `40 cores`.

Thanks

**Comment by rcedgar** [comment]
1. Muscle v5 only supports FASTA and EFA output formats, you need to use a third-party tool to convert formats.

2. That line reports the amount of RAM and CPU cores available, not the number actually used, this will be shown later as the command progresses. You can use the `-threads N` option to set a maximum number of cores.

**Comment by ErisonChen** [comment]
> 2. That line reports the amount of RAM and CPU cores available, not the number actually used, this will be shown later as the command progresses. You can use the `-threads N` option to set a maximum number of cores.

hi @rcedgar;
How can we limit the maximum amount of RAM used. 
Today there was a program that spiked from 5G to 200G and then was killed and terminated. 
Our compute nodes can't handle such a high memory spike.

Thanks so much.

**Comment by rcedgar** [comment]
Currently, muscle v5 does not provide command line options to specify the maximum amount of RAM. If you are using -align, then -super5 generally uses less RAM. By trying some examples, you can estimate roughly how much RAM will be used by your input data as a function of sequence length and number of sequences, then you can filter out datasets which are too big.
