### ISSUE TITLE
double free or corruption (!prev)eriors

### ISSUE THREAD

**Issue by Adarsh931** [rcedgar/muscle#34]
I was using muscle5 for alignment of around 10k sequences, I am getting the following error:
```
muscle 5.1.linux64 [12f0e2]  528Gb RAM, 56 cores
Built Jan 13 2022 23:17:13
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

Input: 9988 seqs, avg length 745, max 3209


WARNING: >1k sequences, may be slow or use excessive memory, consider using -super5

00:40 4.9Gb  CPU has 56 cores, running 36 threads
double free or corruption (!prev)eriors
```

**Comment by rcedgar** [comment]
Does this error reproduce every time you try? I would be glad to take a look if you post the input somewhere I can download it -- if so, please try binary search to reduce the number of input sequences as follows: divided the input in half, try each half, if one fails then repeat with the half.
