### ISSUE TITLE
Cannot open xxx.fas , errno=2 No such file or directory

### ISSUE THREAD

**Issue by jljy47** [rcedgar/muscle#41]
Hi, I have successfully run Muscle 5.1.win64 on Windows once before. But this time, all files (including the one which succeeded before) failed to run and shows like:
---Fatal Error---
Cannot open xxx.fas , errno=2 No such file or directory

And I have checked the .fas or .fasta files. They all have right informations and can be open by other Editor softwares like BioEdit.

Can anyone help me?Thanks a lot.

Muscle &File address:
C:\Users\USER\Desktop\software\desktop\Muscle\muscle-5.1\muscle5.1.win64.exe

Code:
C:\Users\USER\Desktop\software\desktop\Muscle\muscle-5.1\muscle5.1.win64.exe -align ES_Mitos_match_unPaired_73_cob.fas -output test.fasta

.fas file is like: 
>SDHF_76M_cob	
ATGAATAAATCTATACGAACTTATCACCCATTATTTAAAATTGCCAATAATGCTTAATTGAT????????????????????????????????????????GATCATTATTAGGAATTTGTTTAGTAAAACAAATCCTAACAGGAATATTYTTAGCCATACATTATAGCCCCAATATTKAACAAGCATTTTCTAGAGTAGCAMATATTTGTCGAGACGTAAATWATGGRTGACTACTTCGAGTCTTGCATGCCAATGGAGCATCTGTATTTTTTCTT????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????CTTGAGGACAAATATCTTTTTCTAGGGTGCCGGTGTCATAGTTTTTTGGAGCAGCCGTTCCATATTTAGGTACTGATCTAGTACAATGAGTATGAGGKGGCTTCGCTGTAGACAAYGCYACAYTAAACCGATTCTTTACTTTACATTTTTTAYTACCATTTATCATTACWGCACTTGTATTAATWCACTTAKTATTTCTTCACCAAACAGGATCAAAYAAMCCCATAGSAATAAACAGAAACATTGATAAAATTCCCTTCCATCCATACTTCACAACAAAAGACATTGTAGGRTTYATTATTATAWTTATAWTATTAKSCWTTTTATCACTCAAAGAACCATATATTCTTGGAGATCCTGACAATTTCACACCAGCTAATCCCTTAGTTACTCCTGTTCACATTCAACCTGAATGATATTTTCTATTTGCATATGCAATTTTACGATCAATTCCTAAYAAATTAGGRGGAGTAATCGCYYTAGTAATATCAATTGCYATCTTATTTATTATACCATTATATAAATCAAATTTTCGAAGAATACAATTTTACCCAATTAATCAAGCATACTTCTGAACAATAACAAATACTGTAATTTTATTAACATGAATTGGAGCACGACCAGTAGAAGAACCTTATATCATCACAGGCCAATTATTAACTACAATTTATTTTAGATATTATCTTATAATTCCTTTTATTACCAAAACATGAGAAACATAGACTTATG	
>SDHF_76R_cob	
ATGAATAAAYCTATACGAACTCATCAYCCATTATTTAAAATTGCTAATAATGATTTAKTTGACCTTCCAGCCCCTTCAAATATTACAACCTGATGAAATTTTGAATCACTGTTAGGAATCTGCTTAATAATACAAATTTTAACGGGAATATTTCTAGCTATACATTATAGCCCAAACATTKAGCAAGCGTTTTCTAGAGTAACACACATTTGTCGAG???????????????????????????????????????????????????????????????????????????????TGGTCGASGAKWWYRSWAKRCRWSAWTMAAATTAATACATACCTGATTTGTAGGTGTAATAATTTTATTCATCACTATAGCAACAGCTTTTGTAGGGTATGTCTTACCTTGAGGACAAATATCTTTTTGAGGGGCCACTGTAATTACTAACCTTTTA?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????CTGTTTCTTCACYAWMYARSATCAAAYAACCCCTTTAGGAATAAATAGAAACATCGACAAAATCCCCTTCCATCCATATTTCACAACAAAAGACATTGTTGGATTCATCATTATATTTATAATATTATCTATTTTATCACTAAAAGAACCTTATATTCTAGGAGAYCCCGACAATTTCACACCAGCYAATCCTTTAGTTACYCCYATYCACATTCAACCTGAATGATATTTTCTATTTGCATACGCAATTTTACGATCAATTCCTAATAAATTAGGGGGAGTAATAGCCTTAGTGATATCAATTGCCATCTTATTTATTATACCATTATATAAATCAAATTTCCGAAGAATTCAATYCTACCCGATTAATCAAATATACTTCTGAATAATAGTAAACACTGTAATCTTATTAACATGAATTGGAGCACGACCAGTAGNNNNNNNNNNNTACAGGTCAATTATTAACTACASTMTATKTCAGATACTACMTWATWATTYCYTCAATTACTAAAATATGAGAAAATCTTAYCAAAT	
>SDHF_76S_cob	
ATGAATAAATCTATACGAAYTWATCATCCATTATTTAAAATCGCCAATAATGCTTTAATTGATCTTCCGATCTCGAATAATTGAACATGATGAAACTTTGGATCATTATTAGGAATTTGTTTAGTAATACAAATCCTAACCGGAATATTCTTAGCCATACATTATAGACCTAATATCGAACAAGCATTTTCTAGAGTAGCACACATTTGTCGAGACGTAAATTATGGATGACTACTACGAACCTTACATGCTAATGGAGCMTCTATATTTTTTCTTTGTATTTACTTACA??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????CRRYKGSATCAAGATAACCCTTTAGGAATAAATAGAAACATCGACAAAATCCCCTTYCAYCCATATTWCACAACAAAAGAYATTGTTGGATTCATYATTATATTYATAVTAYTRTCHATTTTATCACTMAAAGAACCNNNNTTATATTCTAGGAGAYCCYGACAATTTTACACCGGCTAATCCTTTAGTTACCCCTGTTCACATTCAACCTGAATGGTACTTCCTATTTGCATATGCAATTTTACGATCAATTCCTAACAAATTAGGAGGAGTAATCGCCTTAGCAATATCAATTGCTATTCTATTTATCATACCATTACATAAATCAAATTTCCGAAGAATTCAATTTTACCCCAATT???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????	
>SDHF_76Z_cob	
?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????ATAGTGTAAGACATCATTCAAATTAATACAGACCTGATTTGTAGGTGTAATAATTTTATTCATCACTATAGCAACAGCTTTTGTAGGATATGTCTTACCTTGAGGACAAATATCTTTTTGAGGGGCCACTGTAATTACTAACCTTTTATC???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????AATTCTCCATGGGAACGTACTTATATAATAATTCCCTCAATTACTAAAATATGAGAAAATCTTACCAAAT

**Comment by rcedgar** [comment]
The error is "No such file or directory", this means the file name is incorrect. Check the file name and path, it has nothing to do with the contents of the file.

**Comment by jljy47** [comment]
Thanks~ I have solved it by changing the path before running the command. (in cmd on Windows)

#The right way is to set the path before the running command
>cd C:\...\Muscle       #set your Muscle folder path
>muscle5.1.win64.exe -align xxx.fas -output xxx)clustal.fas    #put your .fas in the same folder

I didn't change the path at the beginning so my PC can find Muscle.exe but the Wrong path is still in the /User path so that it cannot find the .fas file.

The error  "No such file or directory" is also the same hint when your .fas file name is wrong. For the newer to check which kind is your mistake. 

Thanks for helping by the owner timely. And hope every user can enjoy using such a smart and quick software in your study~~~

**Comment by jljy47** [comment]
Thank you so much for answering this question so fast and helping me a lot.
I have just sovled this problem by setting the working path into the Muscle folder and then it runs correctly.

#Wrong path is still in the /User path so that it cannot find the .fas file.





#The right way is to set the path before the running command
&gt;cd your Muscle folder path
&gt;muscle5.1.win64.exe -align xxx.fas -output xxx)clustal.fas





Thank you so much~
But I have not find my question issue one Github. If next newer meet this problem, maybe the reason is this or the wrong file name like you said. They might be the same hint.
Thx for helping.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rcedgar/muscle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月29日(星期一) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [rcedgar/muscle] Cannot open xxx.fas , errno=2 No such file or directory (Issue #41)





 
The error is "No such file or directory", this means the file name is incorrect. Check the file name and path, it has nothing to do with the contents of the file.
