### ISSUE TITLE
automatically reverse-complement nt sequences

### ISSUE THREAD

**Issue by TDDB-limagrain** [rcedgar/muscle#43]
Hi @rcedgar,
thanks a ton for your efforts to provide useful tools to the community!

I was interested in switching from MAFFT to MUSCLE5 for large alignments of virus genomes.
There is feature in MAFFT (option --adjustdirection) which is able to reverse complement some sequences (quite useful because some similar virus genomes may have been deposited in different orientations in NCBI nuccore for example).
Do you think it could be implemented as well in MUSCLE5?

Best regards,

Thomas

**Comment by rcedgar** [comment]
Currently muscle5 does not work well with long sequences, there is a limit around 20k where the code fails, so it will not work for longer genomes such as coronaviruses. Regarding a reverse-complement feature, IMO this does not belong in a multiple aligner module, this is a separate task which should be done by a separate tool. Usearch has a command for this [https://drive5.com/usearch/manual/cmd_orient.html](https://drive5.com/usearch/manual/cmd_orient.html).

**Comment by TDDB-limagrain** [comment]
Many thanks for the reply and advices, much appreciated.

I am working with 6 to 7 Kb RNA virus, I guess that should not be a problem. I will indeed go to Usearch for the task.

Best regards!
