### ISSUE TITLE
Minor: interface change from 3.8 to 5.1 may benefit from more helpful error message

### ISSUE THREAD

**Issue by jweile** [rcedgar/muscle#46]
This is very minor: Using the old syntax `muscle -in input.fasta -out output.aln` is not compatible anymore with version 5, but the error message does not point in the right direction. Instead of 
```
Invalid command line
Unknown option in
```
It may be helpful to show something like
```
The option `--in` is no longer supported. Please use `--align` instead.
```

**Comment by rcedgar** [comment]
Good idea thanks for the feedback.
