### ISSUE TITLE
Segmentation fault while running muscle

### ISSUE THREAD

**Issue by navkahlon240** [rcedgar/muscle#49]
muscle -in combined.fasta -out align.fasta

MUSCLE v3.8.1551 by Robert C. Edgar

http://www.drive5.com/muscle
This software is donated to the public domain.
Please cite: Edgar, R.C. Nucleic Acids Res 32(5), 1792-97.

combined 74665 seqs, lengths min 38, max 11532, avg 307
Segmentation fault

Can you help me out with this?

**Comment by rcedgar** [comment]
this repo is v5, you're using v3. this set is too large for v3. at a guess v5 should be able to handle this set, though this is a large set and the sequence length is very variable, are you sure these are globally alignable?

**Comment by navkahlon240** [comment]
What kind of data is globally alignable? How can we check whether data is globally alignable or not?

**Comment by rcedgar** [comment]
global alignment = all letters from all sequences are included in the order they appear in the sequence. if there are any of the following: transversions, inversions, or long duplications, insertions or deletion events between two sequences, then a global alignment will be somewhere between (a) align some sequence incorrectly and (b) totally wrong.
