### ISSUE TITLE
build not fully static with -fopenmp -pthread

### ISSUE THREAD

**Issue by joelb123** [rcedgar/muscle#5]
openmp is from GCC and pthread are part of glibc.  The makefile specifies -static for link, but the resulting binaries will not be fully static; I believe this is true for the distributed binaries, making it a problem that binary users will find a problem with.

>/usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0/libgomp.a(oacc-profiling.o): in function `goacc_profiling_initialize':
>/var/tmp/portage/sys-devel/gcc-11.1.0-r1/work/gcc-11.1.0/libgomp/oacc-profiling.c:137: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

The simple thing is to remove -static from the Makefile link.  There are ways to build fully static for distribution, but they are more complicated than reflected in the makefile.

**Comment by rcedgar** [comment]
Closing issue because there have been no reports from users that this is a problem in practice.
