### ISSUE TITLE
Aarch64 muscle built from source fails

### ISSUE THREAD

**Issue by lukaszsobala** [rcedgar/muscle#52]
Hello,

Since only a Mac arm64 version is provided, I tried to build my own for a distribution on aarch64 ubuntu.

The build finished with zero errors, but when I ran muscle with no parameters I git this:

```
---Fatal error---
myutils.cpp(122) assert failed: sizeof(void *) == 4
```

**Comment by lukaszsobala** [comment]
I changed that line, recompiled and the error is the same. I know next to nothing about programming, so this log won't tell me much, but please tell me what I should post. `test.cpp` doesn't exist but other files that start with `test` do.

**Comment by rcedgar** [comment]
try `cpp -dM xxx.cpp > output.txt` where xxx is any `*.cpp` file, the source file must exist but it's actually ignored, post `output.txt` somewhere I can take a look

**Comment by lukaszsobala** [comment]
Please take a look at your repository, the only "test" files that are in /src are:
`testfb.cpp  testlog.cpp  testscoretype.cpp`

Anyway, here are the lists from all three:
[testfb.txt](https://github.com/rcedgar/muscle/files/10974556/testfb.txt)
[testlog.txt](https://github.com/rcedgar/muscle/files/10974557/testlog.txt)
[testscoretype.txt](https://github.com/rcedgar/muscle/files/10974558/testscoretype.txt)

I hope this is useful!

**Comment by rcedgar** [comment]
Looks like my guess was right, if you change line 14 in `myutils.h` to look like this it should work:
`#if defined(__x86_64__) || defined(_M_X64) || defined(__arm64__) || defined(__aarch64__)`

**Comment by rcedgar** [comment]
this would need an aarch64 github action to do the build, that should be very similar to Ubuntu if you add an action and issue a pull request that could work

**Comment by CaldoSmash** [comment]
Does this solution work? I’m trying to help my girlfriend with her bioinformatics for her degree. I’m an IT technician not a programmer so if I change line 14 in myutils.h and recompile the code should muscle work with aarch64

**Comment by lukaszsobala** [comment]
Yes. When I compile it locally it works perfectly. I tried to create a PR but anything I tried failed. I don't really know how to use Github actions.

**Comment by martin-g** [comment]
I will work on a new Github Action CI job for Linux ARM64!

**Comment by martin-g** [comment]
https://github.com/rcedgar/muscle/pull/73

**Comment by martin-g** [comment]
By the way at Bioconda Linux ARM64 [CI](https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/110998/workflows/5dc50569-ee79-4976-80f3-885ae4cf2406/jobs/181817?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary) I get this error:
```
12:37:16 [32mBIOCONDA INFO[0m (OUT) $BUILD_PREFIX/bin/aarch64-conda-linux-gnu-c++ -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem $PREFIX/include -DNDEBUG -pthread -fvisibility-inlines-hidden -fmessage-length=0 -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/muscle-5.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -O3 -fopenmp -ffast-math -c -o Linux/testlog.o testlog.cpp[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT) In file included from testlog.cpp:2:[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT) In function 'uint64_t GetClockTicks()',[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT)     inlined from 'void cmd_testlog()' at testlog.cpp:71:26:[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT) timing.h:26:9: error: impossible constraint in 'asm'[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT)    26 |         __asm__ __volatile__ ("rdtsc" : "=a" (lo), "=d" (hi));[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT)       |         ^~~~~~~[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT) In function 'uint64_t GetClockTicks()',[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT)     inlined from 'void cmd_testlog()' at testlog.cpp:83:26:[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT) timing.h:26:9: error: impossible constraint in 'asm'[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT)    26 |         __asm__ __volatile__ ("rdtsc" : "=a" (lo), "=d" (hi));[0m
12:37:16 [32mBIOCONDA INFO[0m (OUT)       |         ^~~~~~~[0m
```

I don't get this error at Github Actions and on my local build ...

**Comment by rcedgar** [comment]
This is coming from the GetClockTicks() function defined in timing.h, it's very old code from a time when it was tricky to get get the value of the CPU clock (RDTSC instruction). GCC versions >=5 have an __rdtsc() intrinsic, if you edit timing.h to replace the assembler with the intrinsic for the appropriate version of GetClockTicks() it will probably work. The problem with this fix is that it will be necessary to re-test all the build variations on other platforms.

**Comment by martin-g** [comment]
Thanks, @rcedgar !
The problem is that I cannot reproduce it easily, so I don't feel confident changing the code.
I am trying to find what is different at Bioconda CI.

**Comment by martin-g** [comment]
I found the reason!
Bioconda uses tag `5.1` - https://github.com/rcedgar/muscle/blame/v5.1/src/timing.h
But `main` and `5.1.0` has this https://github.com/rcedgar/muscle/commit/d5b2c520998571b00b19fdfa2d4d0a2ad9b850c6 - it disables the content inside `if / endif`

**Comment by martin-g** [comment]
If you plan to tag a new version with the improvement in `myutils.h` then I will wait for it!
Otherwise I could use either `5.1.0` or a .patch for both `myutils.h` and `timings.h`!

**Comment by rcedgar** [comment]
Sorry, I don't follow, which improvement in myutils.h, and what do you mean by "tag"? If you mean post a new release, then I have no plans to do that in the near future.

**Comment by martin-g** [comment]
I meant the addition of __aarch64__ in the PR that fixes the build on Linux
ARM64.

And yes, I meant a new Git tag, i. e. a release.

**Comment by martin-g** [comment]
Bioconda now provides `linux-aarch64` build for `muscle` - https://anaconda.org/bioconda/muscle !
https://github.com/bioconda/bioconda-recipes/pull/46525
