### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by nsoranzo** [rcedgar/muscle#6]
Hi @rcedgar,
thanks for publishing MUSCLE on GitHub! I'm [working](https://github.com/bioconda/bioconda-recipes/pull/29550) on updating the MUSCLE package on [Bioconda](https://bioconda.github.io/). Bioconda strongly [recommends](https://bioconda.github.io/contributor/linting.html#uses-vcs-url) using releases (or at least Git tags) in package recipes, which is also general good practice for reproducibility. Would you please be able to [tag a release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository) on GitHub?

**Comment by rcedgar** [comment]
Hi @nsoranzo thanks for the feedback! Implementing releases per standard github conventions is on my to-do list, but it will probably be a while before I get to it as I'm working on extensive improvements to the algorithm. It's premature to update muscle in widely-used distributions such as Debian and Bioconda, this should be regarded as an experimental/beta release which has yet been widely tested in practice.

**Comment by nsoranzo** [comment]
OK, thanks for the reply! I'll mark the Bioconda update as Work In Progress for the time being.

**Comment by colinbrislawn** [comment]
Just saw your online talk about MUSCLE v5, and came to check if it was shipping on Bioconda! 📦 🐍 

For what it's worth, the bioRxiv preprint has [already been cited](https://scholar.google.com/scholar?cites=1095732105608351900), and you could tag a release candidate as `v5.0.1428-rc.1` to show it's still in beta.

**Comment by nsoranzo** [comment]
[v5.0.1428](https://github.com/rcedgar/muscle/releases/tag/v5.0.1428) is out, closing.
