### ISSUE TITLE
Memory Object >4Gb error

### ISSUE THREAD

**Issue by czhou135** [rcedgar/muscle#60]
Hi, I'm not very familiar with super5, but I ran an alignment with 12k sequences w ~900aa on average per sequence. I gave the program 20G of memory to work with. I got the following error:

Elapsed time 10:14:33
Max memory 6.1Gb

---Fatal error---
Memory object >4Gb, probably due to long sequences

Does this error mean that super5 is unable to run an alignment on this dataset or is there a fix? Should I switch to a different alignment software? Thanks!

**Comment by rcedgar** [comment]
Note "...probably due to long sequences "

What is the maximum length?
R

**Comment by czhou135** [comment]
The maximum length was 2868 aa, would that be too long?

**Comment by rcedgar** [comment]
Could be, I can check if you post the sequences. What are the sequences? Can't you trim them to a globally alignable region? The length variation is pretty big to get a good MSA from any algorithm.

**Comment by czhou135** [comment]
These are representative tRNA synthetases from across the tree of life, but I need the alignment to construct a phylogenetic tree. 
[sequences.txt](https://github.com/rcedgar/muscle/files/11751636/sequences.txt)

**Comment by rcedgar** [comment]
The memory allocation fails because the alignment exceeds 50,000 columns at an intermediate step. The final alignment would probably have far more columns. These sequences are too far diverged to make a reasonable alignment, there is no chance of building a good tree from them.

**Comment by czhou135** [comment]
Thanks for the responses, just wanted to update we've narrowed the study down to a specific domain with less length variation and muscle works for us now!
