### ISSUE TITLE
@ in output filename required for -perm all with -super5

### ISSUE THREAD

**Issue by DeadlineWasYesterday** [rcedgar/muscle#62]
According to the documentation, it should just make one ensemble .efa file with all four guide trees if I don't include the '@' wildcard. But my muscle 5.1 errors out forcing me to use an @ to write 4 separate files which I then have to join with -fa2efa. Is this intended?

**Comment by rcedgar** [comment]
This is a documentation problem, I will add the following text to the usage help in the next build:
<pre>
Note -super5 does not support .efa output, to get an ensemble you can
  (1) run several times with different -perm and -perturb options, or
  (2) use <i>-perm all</i>, then four output files will be generated, one for
        each guide tree permutation (use @ in the output filename).
</pre>
