### ISSUE TITLE
Automatic optimal number of threads

### ISSUE THREAD

**Issue by dreyes17** [rcedgar/muscle#64]
Hello, 

I am integrating Muscle in a platform that is used by people that don't necessarily know how to program. In order to optimally use the server resources I normally calculate the number of threads necessary for each program automatically.

Reading your paper I guess that the parallelized part of the algorithm is the calculation of matrix M. If this is right the number of threads to optimally use resources should be a multiple of: <number of pairs in MSA replicas> * <number of MSA replicas>.

I have two doubts about this:

1. It is very difficult to know what will be the length of the replicas MSA. Is it impossible to know in advance?
2. All the MSA replicas might not have the same length. For this purpose I should select the largest?

**Comment by rcedgar** [comment]
I would not worry about trying to set the number of threads. By default,  muscle uses minimum(20, number of CPU cores), this should work fine.
