### ISSUE TITLE
Specifying threads

### ISSUE THREAD

**Issue by bioinfo007** [rcedgar/muscle#66]
Is it possible to specify threads and perform parallel processing, i have a large data set that I want to submit via sbatch on HPC, but there is no clear help for specifying threads. Please respond with a suitable solution. As processing a single file with around 600 sequences is taking much time, even with specifying 80 cores. It seems muscle5 is not able to use all the 80 cores.
Thank you

**Comment by rcedgar** [comment]
the `-threads N` option specifies the number of threads, default is min(20, number_of_CPU_cores).
you verify muscle is using multiple threads using the `top` command, e.g. it will show 2000% CPU if it us using 20 cores.
how long are the sequences? time and memory scale like L^2 where L is the sequence length, if they are much longer than around 1,000 letters, then it may be slow.

**Comment by zersalsion** [comment]
It seems to be that `-super5` ignores the threads option.

**Comment by rcedgar** [comment]
It should support the -threads option, I have tested this extensively.
please double-check, if you still believe there is a problem please provide test data and script to reproduce the symptom.

**Comment by zersalsion** [comment]
You are right. muscle only has a relative long startup phase that is single threaded. After a couple of minutes, it starts to use the defined number of cores.
