### ISSUE TITLE
Segmentation fault (core dumped)riors

### ISSUE THREAD

**Issue by MHassanSaeed** [rcedgar/muscle#69]
**Command used:**
`muscle -align 1.fasta -output alignment.fasta`

**Error information:**
muscle 5.1.linux64 []  528Gb RAM, 56 cores
Built Feb 24 2022 03:16:15
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

WARNING: 7 duplicate labels

Input: 241 seqs, avg length 324490, max 2766791

00:00 133Mb  CPU has 56 cores, running 24 threads
Segmentation fault (core dumped)riors

**Comment by rcedgar** [comment]
please see issue #31

**Comment by rcedgar** [comment]
also, I think it is unlikely sequences of length ~300k are globally alignable, I can't think of an example of biological sequences this long which don't have re-arrangement events
