### ISSUE TITLE
Fatal error: allocflat.cpp(15) assert failed: uint64(Size) == Size64

### ISSUE THREAD

**Issue by m-leitman** [rcedgar/muscle#75]
Hi! This is my first time using muscle. I am on a macOS with the arm64 version. I ran the command ./muscle -super5 all_complete_cut.fa -output alfn.afa. The output is as follows: muscle 5.1.osxarm64 [ef62d8-dirty]  17.2Gb RAM, 8 cores
Built Jan 15 2022 11:59:50
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

Input: 5301 seqs, length avg 52390 max 372876

WARNING: Sequence length >5k may require excessive memory

00:02 337Mb   100.0% Derep 5263 uniques, 37 dupes
00:02 342Mb  CPU has 8 cores, running 8 threads                      

./muscle -super5 all_complete_cut.fa -output alfn.afa
Elapsed time 00:02
Max memory 342Mb

---Fatal error---
allocflat.cpp(15) assert failed: uint64(Size) == Size64

What is going wrong?

**Comment by rcedgar** [comment]
As suggested by the warning message, these sequences are *much* too long,
they are surely not suitable for global multiple alignment.
R
