### ISSUE TITLE
2 nts are "cut" from the rest.

### ISSUE THREAD

**Issue by 0xorial** [rcedgar/muscle#79]
I am aligning a very simple example with exact match (see below). For some reason 2 nucleotides are separated from the rest and placed in the very end. Input and output attached.
![image](https://github.com/user-attachments/assets/2d5c48f1-fe1a-4f48-adc7-e7078e8646a5)
[Archive.zip](https://github.com/user-attachments/files/16250634/Archive.zip)

**Comment by rcedgar** [comment]
I guess your question is "why and is this a bug".
why = choice of terminal gap penalties (or here, HMM transition probability into Exit state, which is essentially the same thing).
is this a bug = no
of course this example looks "wrong", but for any choice of gap penalty schemes you can always find "obviously wrong" cases.
such is life when algorithms use highly simplified an unrealistic models of evolution.

**Comment by 0xorial** [comment]
hehe, that was indeed my question. thanks for clarifying!
