### ISSUE TITLE
Update bioconda-recipe to support osx-arm64

### ISSUE THREAD

**Issue by isaacovercast** [rcedgar/muscle#80]
Hello and thanks so much for muscle, it is a massively useful tool!

The bioconda folks https://github.com/bioconda/bioconda-recipes/issues/33333#issuecomment-2221176852 (Mac M1/M2). Enabling the build for this platform is currently 'opt-in' so you have to add a flag to the meta.yaml (documented at the link). I have updated my own package following this direction and it works fine.

The bioconda folks said that I could update recipes for packages that I don't maintain, and I'm happy to do that, but it makes me a bit nervous to mess with other people's stuff without permission, so wanted to check here if you are interested to do the update, or if you mind if I do it, or if there's a reason it wouldn't be a good idea to do.

Thanks again for muscle!

**Comment by rcedgar** [comment]
Please go ahead! I'm very happy if people figure out how to make package recipes for my software, I know very little about how all that works

**Comment by isaacovercast** [comment]
Ok great! The bioconda muscle v5 package should build osx-arm64 now, I will test it soon and close this issue after i verify it works.

Here's the bioconda recipe PR: https://github.com/bioconda/bioconda-recipes/pull/50213

**Comment by isaacovercast** [comment]
I did not test comprehensively, but a simple MSA (`-align`) works fine.
