### ISSUE TITLE
increase the threads

### ISSUE THREAD

**Issue by chaoyanggu** [rcedgar/muscle#82]
Dear professor, 
  I used to use the v3 to build an phylogenetic tree for a small data. Now I merged a large data, and a failed for running with v3. Please tell me if the v5 could increase the threads, or how can I modify my codes.
  my codes as followings,
   muscle  -maketree -in gene1.aln.fa -out gene1.nj.tree -cluster neighborjoining

Thank you.

**Comment by rcedgar** [comment]
The best way to check if v5 will work on your data is to try running it on your data.

**Comment by chaoyanggu** [comment]
My data contains 3000 gene sequences, please give me a code to build a phylogenetic tree by v5, and I'll test it. Thank you.

**Comment by rcedgar** [comment]
muscle is for multiple sequence alignment, it does not estimate trees.

**Comment by chaoyanggu** [comment]
Sorry， because I saw that there was a maketree option in the v3 version, so I thought muscle could build evolutionary trees.
