### ISSUE TITLE
"illegal hardware instruction" error

### ISSUE THREAD

**Issue by ori-scala** [rcedgar/muscle#83]
After installing the latest MUSCLE version (5.2), I'm getting the following error when trying to run MUSCLE.

`illegal hardware instruction`

I assume it's related to the Apple M series chipset.

This is the output of `muscle --version`

```
muscle 5.2.osx64 [-]  34.4Gb RAM, 10 cores
Built Nov  3 2024 04:21:53
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com/
```

**Comment by rcedgar** [comment]
I don't have an Apple M for testing, but the binary did compile successfully using the GitHub action runner for M as you can see here: [https://github.com/rcedgar/muscle/actions](https://github.com/rcedgar/muscle/actions). The release binary is an asset from this action, so assuming you downloaded the binary from the GitHub release I have no idea what would cause this or how to trouble-shoot. Can you try recompiling from source?

**Comment by rcedgar** [comment]
Also, can you try running a few different commands with small input, say 2 or 3 sequences, to see if the error always happens or is specific to one command or option?

**Comment by rcedgar** [comment]
A good one to try is
<pre>
muscle -msastats aln.afa
</pre>
because this doesn't use any alignment code

**Comment by ori-scala** [comment]
I didn't download it directly from the github release but rather installed it using conda by running:

`conda install bioconda::muscle==5.2.0 -y`

Then I run `muscle --help` and I get:

```
muscle --help
[1]    14859 illegal hardware instruction  muscle --help
```


Then, I downgrade using:

`conda install bioconda::muscle==5.1.0 -y`

and `muscle --help` works again with the following output:

```
muscle --help

muscle 5.1.osx64 []  34.4Gb RAM, 10 cores
Built May 15 2023 21:29:02
(C) Copyright 2004-2021 Robert C. Edgar.
https://drive5.com

This is help.txt
```

**Comment by rcedgar** [comment]
Try downloading the v5.2 binary from github. If this works & bioconda install does not work, then this is a bioconda problem.

**Comment by ori-scala** [comment]
Who owns the bioconda releases? I'd much rather them to fix it :)

**Comment by rcedgar** [comment]
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/usearch/meta.yaml

**Comment by ori-scala** [comment]
Thanks!
