### ISSUE TITLE
Allow `-` as a stand-in for stdin and stdout.

### ISSUE THREAD

**Issue by apcamargo** [rcedgar/muscle#84]
Since it's pretty common to have aligners taking from `stdin` or passing the alignment to a downstream command via `stdout`, it would be nice to be able to use `-` as a stand-in for `stdin`/`stdout`.

**Comment by rcedgar** [comment]
You can use `/dev/stdin` and `/dev/stdout`. Since `-` is a valid filename, IMO it would be a bad idea to it as a special case in that way.

**Comment by apcamargo** [comment]
That's what I do. I figured out it could be useful to open up this issue because `-` is very common and people may be used to it. But it's not a big deal, honestly.
